export * from './config.interfaces'
export * from './file.interfaces'
export * from './pagination.interfaces'
export * from './mutation-response.interfaces'
export * from './custom.interfaces'
export * from './custom-response.interfaces'
